spring:
  #===========#
  #   MySQL   #
  #===========#
  datasource:
    user:
      jdbc-url: jdbc:mysql://localhost:3307/jinia_blog_user?serverTimezone=Asia/Seoul
      username: root
      password: 1
      driver-class-name: com.mysql.cj.jdbc.Driver