---
# Source: mysql-innodbcluster/templates/service_account_cluster.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mycluster-sa
  namespace: default
---
# Source: mysql-innodbcluster/templates/cluster_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-cluster-secret
  namespace: default
stringData:
  rootUser: "root"
  rootHost: "%"
  rootPassword: "password"
---
# Source: mysql-innodbcluster/templates/deployment_cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  namespace: default
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 1
  secretName: mycluster-cluster-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 9.1.0
  serviceAccountName: mycluster-sa
  # mycnf
  # datadirVolumeClaimTemplate
  # datadirPermissions
  # Keyring
  # Init DB
  # Backup Profiles
  # Backup Schedules
  # Pod Spec
  # Pod Labels
  # Pod Annotations
  # Logs
  # Service
  # Metrics
  # Read Replicas