spring:
  #===========#
  #   MySQL   #
  #===========#
  datasource:
    article:
      jdbc-url: jdbc:mysql://localhost/jinia_blog_article?serverTimezone=Asia/Seoul
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
