apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3200"

    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/etc/tempo.yml"]
          ports:
            - containerPort: 3200
            - containerPort: 4318
          volumeMounts:
            - name: config-volume
              mountPath: /etc/tempo.yml
              subPath: tempo-config.yml
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: config-volume
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: tempo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: http-tempo
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  selector:
    app: tempo