server:
  port: 7777

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/blog_core?allowPublicKeyRetrieval=true&useSSL=false
    username: root

  flyway:
    url: jdbc:mysql://localhost:3307/blog_core?allowPublicKeyRetrieval=true&useSSL=false
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validateMigrationNaming: true
    locations: db.migration.blogcore

logging:
  level:
    org:
      springframework:
        r2dbc: INFO