server:
  port: 7777

spring:
  #===========#
  #   MySQL   #
  #===========#
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/jinia_blog_article?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
