version: "3"
services:
  monolith-main:
    ports:
      - "7777:7777"
      - "7778:7778"

    environment:
      JAVA_TOOL_OPTIONS: -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=7778 -Dcom.sun.management.jmxremote.rmi.port=7778 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=$DEFAULT_IP  -Xms2G -Xmx2G
      SPRING_APPLICATION_JSON: '{
  "spring": {
    "datasource": {
      "user": {
        "driver-class-name": "com.mysql.cj.jdbc.Driver",
        "jdbc-url": "jdbc:mysql://jiniaslog-db/jiniaslog_user?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8",
        "username": "root",
        "password": ""
      },
      "blog": {
        "driver-class-name": "com.mysql.cj.jdbc.Driver",
        "jdbc-url": "jdbc:mysql://jiniaslog-db/jiniaslog_blog?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8",
        "username": "root",
        "password": ""
      },
      "memo": {
        "driver-class-name": "com.mysql.cj.jdbc.Driver",
        "jdbc-url": "jdbc:mysql://jiniaslog-db/jiniaslog_memo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8",
        "username": "root",
        "password": ""
        }
    }
  }
}'
    container_name: jinias_log_monolith_main
    build:
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      jiniaslog-db:
        condition: service_healthy
    restart: always
    networks:
      - internal-network

  jiniaslog-db:
    image: mysql:8.0.39
    restart: always
    networks:
      - internal-network
    ports:
        - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: jiniaslog_blog
    volumes:
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 1s
      retries: 120

  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - internal-network
    ports:
      - "8882:6379"
    command: ["bash", "-c", "echo never > /sys/kernel/mm/transparent_hugepage/enabled && redis-server"]
    privileged: true

networks:
  internal-network:
    driver: bridge
