version: "3"
services:
  db_mysql_1:
    ports:
      - "3307:3306"
    container_name: jinias_log_mysql_core
    image: mysql:8.0.34
    restart: always
    networks:
      - internal-network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "blog_core"
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 1s
      retries: 120
    deploy:
      resources:
        limits:
          cpus: "1"

networks:
  internal-network:
    driver: bridge
