
### 1. 임시 아티클 생성 테스트
POST http://localhost:7777/articles/temp
Content-Type: application/json

{
  "title": "ㅇㅇㅇㅇㅇ",
  "content": "",
  "thumbnailUrl": "",
  "writerId": 1,
  "categoryId": 0
}


### 2. 임시 아티클 조회 테스트
GET http://localhost:7777/article/temp
