spring:
  #===========#
  #   MySQL   #
  #===========#
  datasource:
    id:
      jdbc-url: jdbc:mysql://localhost/jinia_blog_id?serverTimezone=Asia/Seoul
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  ddl:
    auto:
      value: create-drop