spring:
  #===========#
  #   MySQL   #
  #===========#
  datasource:
    id:
      jdbc-url: jdbc:mysql://localhost:3307/jinia_blog_id?serverTimezone=Asia/Seoul
      username: root
      password: 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      show-sql: true

jpa:
  ddl:
    auto:
      value: validate
